if [ ! -d "./logs" ]; then
    mkdir ./logs
fi

data_version=10_07_2024_16_06_02

for target_node in 160MW
do
    if [ ! -d "./logs/LongForecasting_indv_"$data_version ]; then
        mkdir ./logs/LongForecasting_indv_$data_version
    fi
    
    if [ ! -d "./logs/LongForecasting_indv_"$data_version"/"$target_node ]; then
        mkdir ./logs/LongForecasting_indv_"$data_version"/$target_node
    fi
    seq_len=96
    model_name=PatchTST

    root_path_name=./dataset/
    data_path_name=waterG_allNodes.csv
    model_id_name=waterG_allNodes
    data_name=custom

    features=M
    enc_in=324

    random_seed=2021
    for pred_len in 96 192 336 720
    do
        python -u run_longExp.py \
        --random_seed $random_seed \
        --is_training 1 \
        --root_path $root_path_name \
        --data_path $data_path_name \
        --model_id $model_id_name'_'$seq_len'_'$pred_len \
        --model $model_name \
        --data $data_name \
        --features $features \
        --target $target_node \
        --seq_len $seq_len \
        --pred_len $pred_len \
        --enc_in $enc_in \
        --e_layers 3 \
        --n_heads 16 \
        --d_model 128 \
        --d_ff 256 \
        --dropout 0.2\
        --fc_dropout 0.2\
        --head_dropout 0\
        --patch_len 16\
        --stride 8\
        --des 'Exp' \
        --train_epochs 100\
        --patience 20\
        --individual 1\
        --itr 1 --batch_size 32 --learning_rate 0.0001 --gpu 1 > logs/LongForecasting_indv_"$data_version"/$target_node/$model_name'_'$model_id_name'_'$seq_len'_'$pred_len'_ftr'$features'_individual'.log
    done
done
#original name of waterG_allNodes is /single_file_simtime_05_07_2024_09_25_01.csv, generated by /home/abgo/Desktop/Codes/UTWIN_proj, SWMM, physical model from 1 year(s) rain dataset for all nodes (node name '101' changed to 'OT')
#simulation_start_date="2015/08/19 23:50",simulation_end_date="2016/08/19 23:50"